server {
    server_name cv.shrek-labs.dev;

    listen [::]:443 ssl;
    listen 443 ssl;

    include conf.d/ssl.conf;

    root /var/www/cv;
    index index.html;

    # Serve the static build; fall back to index.html for client-side routing
    location / {
        access_log /var/log/nginx/cv-access.log;
        error_log /var/log/nginx/cv-error.log;

        try_files $uri $uri/ /index.html;
    }
}
